CHANGES
README.markdown
src/Parse.hs
src/Runner/Example.hs
test/ParseSpec.hs
test/Runner/ExampleSpec.hs

A line with only ellipsis now matches any number of consecutive lines.

Make ellipsis matching arbitrary lines.

---

doctest.cabal
src/Extract.hs
src/Interpreter.hs
src/PackageDBs.hs
src/Run.hs
src/Sandbox.hs
test/PackageDBsSpec.hs
test/RunSpec.hs
test/doctests.hs

This is to address a use case we have in stack for multiple custom
package databases, which is not currently supported by the single
sandbox environment variable.

Support HASKELL_PACKAGE_SANDBOXES

---

src/Extract.hs
src/Interpreter.hs
src/Parse.hs
src/Runner.hs
src/Sandbox.hs

This makes it so GHC 7.10 doesn't give back any import warnings, making the whole affair look a little more tidy.

Resolve all build warnings on GHC 7.10.

---

README.markdown

See: https://github.com/sol/doctest/issues/76#issuecomment-56626829 and
continuing conversation for more context.

Document that QuickCheck is a dependency for `prop>` tests

---

doctest.cabal
src/Run.hs

Fixes #148.
Some notes about `code-page`: it's a small little library that I whipped up to solve a similar Unicode-printing issue in `criterion` (see https://github.com/bos/criterion/issues/100 / https://github.com/bos/criterion/pull/125). It depends on solely `base` (and `Win32`, on Windows). On Windows, it uses `bracket` to temporarily change the codepage to CP65001 (which supports UTF-8) and the encoding to `utf8`. On other OSes, it does nothing.
I don't know if you can really test for this, since the bug is an issue with the way Windows consoles display certain characters. But I verified that the example in #148 does print out properly on PowerShell and MSYS2 now.

Print doctest output in a UTF-8-compatible codepage on Windows

---

doctest.cabal

Data.List.Compat was not introduced until `0.7.0`

Update base-compat lower bound

---

CHANGES
README.markdown
src/Options.hs
src/Run.hs
src/Runner.hs
test/OptionsSpec.hs

Add an optional `--fast` flag, which disables `:reload`s between example groups.
Follow-up to #165. Fixes #164.

Add --fast flag

---

doctest.cabal
test/PropertySpec.hs

QuickCheck changed its output slightly at some point between 2.10 and
2.11.3, and this was breaking one of the tests. It's easier to just
update to the newer output and bump the lower bound.

Turn Travis green (hopefully)

---

.travis.yml

This pull request is based on top of #183, so please either merge that first or merge this and close that one. I don't know if Github will do the right thing in the former case, but it's not a thorny rebase even if it doesn't.
The 8.4 builder is allowed to fail, which is just as well because that is a genuine failure. #177 has links to patches that I think will fix it, though! Stay tuned for more PRs on this front.

Add an 8.4 builder to Travis

---

.travis.yml

Previously, we were downloading all GHC versions every build! This
should speed things up.
[Before:  56 min 24 sec total, longest build is 12 min 29 sec.](https://travis-ci.org/sol/doctest/builds/338855738)
[After: 34 min 36 sec total, longest build is 9 min 56 sec.](https://travis-ci.org/quasicomputational/doctest/builds/339109352)

Reduce Travis build time by only downloading specific GHCs.

---

.travis.yml
CHANGES
doctest.cabal
package.yaml
src/Extract.hs
src/Runner.hs

This is a simple application of
https://github.com/hvr/head.hackage/blob/master/patches/doctest-0.13.0.patch,
by Ryan Scott.
It's not quite road-ready yet and the 8.4 builder is still allowed to fail.

GHC 8.4 compatibility.

---

doctest.cabal
package.yaml

Per https://github.com/sol/doctest/pull/194#issuecomment-369461104, @sol no longer wishes to support GHC 7.0 and 7.2. Indicate this explicitly by bumping up the lower version bounds on `base`.

Require base-4.5 or later

---

src/Extract.hs

Since GHC-8.6 plugins need to be initialized on a per module basis.
Without this any modules using plugins fail to compile inside doctest.
This code is adapted from how this was fixed in haddock:
https://github.com/haskell/haddock/pull/983/files#diff-a6119dd2da927bbff2c39eda86cdc733
I have a testcase which I used to verify this is working at: https://github.com/leonschoorl/doctest/blob/load-plugins-test/TestPlugins.hs
But it requires the `ghc-typelits-knownnat` package to be installed, and I don't know how to integrate this into the testsuite.

Initialize GHC plugins

---

CHANGES
doctest.cabal
test/PropertySpec.hs

This changed at some point lately and it's causing our tests to fail.

Fix expected QuickCheck output for failures.

---

.travis.yml

The default's changing in 3.0 and that means that we have to adapt one
way or another. Doing it this way means that we lose coverage with old
Cabal versions, but it keeps the script simpler.
@sol, thoughts? I could do it the other way around (keep old Cabal versions and invoke them differently), but I don't actually know if that'd be valuable, but it'd definitely be a bit annoying to maintain.
And I suppose the third option is to move entirely to v2-style commands, but the tests will need some adaptation.

Explicitly use v1- versions of cabal-install commands.

---

doctest.cabal
package.yaml

I'd entirely forgotten that package.yaml was the source of truth when
bumping the QuickCheck bound. Let's fix that.

Sync package.yaml with doctest.cabal.

---

CHANGES
src/Interpreter.hs
test/RunSpec.hs
test/integration/color/Foo.hs

This is necessary for doctest to operate correctly when the user passes GHC flags like `-fdiagnostics-color=always` to it.
Here is an example module `doctest` fails to process when given with `-fdiagnostics-color=always`.
```haskell
module Foo where
import Data.Maybe
-- | Convert a map into a 2D array.
-- prop> tabulate m !! fromEnum d !! fromEnum p == fromMaybe 0 (lookup (d, p) m)
tabulate :: [((Bool, Bool), Double)] -> [[Double]]
tabulate = undefined
```

Let internal GHC options override user-supplied ones

---

test/RunSpec.hs

This carries on #228, with a failure that's only been exposed now that
the GHC 8.8 builder isn't blocked by dependencies.

Add v1- to cabal-install invocations in the testsuite.

---

.travis.yml
doctest.cabal
package.yaml

This won't actually work because `hsc2hs` doesn't have a compatible release yet. But - when one comes, this PR is just a push of a button away!

GHC 8.10 bounds

---

src/Runner/Example.hs
test/RunSpec.hs
test/Runner/ExampleSpec.hs

Fixes #206 by placing a caret (^) pointing at the character that is different in the result.

Mark position of difference.

---

ghci-wrapper/src/Language/Haskell/GhciWrapper.hs
ghci-wrapper/test/Language/Haskell/GhciWrapperSpec.hs

- Make sure that marker expression works with `-XOverloadedStrings`
- Don't preserve `it` for `evalEcho`

ghci-wrapper enhancements

---

doctest.cabal

http://docs.python.org/ redirects to https://docs.python.org/3/
[skip ci]

.cabal description: update docs.python.org url

---

doctest.cabal
package.yaml

The latter was hand-modified; this is just propagating the change to
the canonical source.

Sync package.yaml with doctest.cabal

---

.github/workflows/ci.yml
CHANGES.markdown
doctest.cabal
ghci-wrapper/src/Language/Haskell/GhciWrapper.hs
package.yaml
src/Extract.hs
src/GhcUtil.hs
src/Options.hs
src/Parse.hs
src/Runner/Example.hs
test/RunSpec.hs

GHC-9.2 compatibility (fix #305)
With this commit, based on @RyanGlScott's patch, building with
```
cabal v1-install --enable-tests --allow-newer=hsc2hs:base --allow-newer=ghc-paths:Cabal
cabal v1-test
```
the tests pass except for the `TemplateHaskell` ones (see below).
This could be due to some commented out code in `src/Extract.hs`,
cutting out the type-checking phase:
```diff
-  mods' <- if needsTemplateHaskellOrQQ mods then enableCompilation mods else return mods
+  --mods' <- if needsTemplateHaskellOrQQ mods then enableCompilation mods else return mods
-  let sortedMods = flattenSCCs (topSortModuleGraph False mods' Nothing)
-  reverse <$> mapM (loadModPlugins >=> parseModule >=> typecheckModule >=> loadModule) sortedMods
+  let sortedMods = flattenSCCs
+#if __GLASGOW_HASKELL__ >= …
```

Support GHC-9.2 (fix #305) (pr #306)

---

.github/workflows/build.yml
doctest.cabal
package.yaml

This will allow us to use branch protection rules.

Add "success" dummy job to github build action

---

.ghci
package.yaml
src/Options.hs
test/doctests.hs

I'm not aware of a clean way to determine the location of `Paths_*` with `cabal v2-*`.  To be able to run `doctest` on `doctest` itself this PR gets rid of any imports of `Paths_doctest`.
This is not ideal but works for now.
I would be very eager to find a way to determine the location of `Paths_*` reliably.  However, I'm not sure if this is currently possible at all.
If somebody really needs `Path_*` then a solution might be to pass the required components in from a smaller driver-wrapper (similar to `driver/Main.hs`).  `doctest` then won't work on the driver, but it will work on the rest of the codebase.

Do not rely on Paths_doctest

---

.github/workflows/publish.yml

@andreasabel with this change, bumping the package version results in two things:
- A tag will be created automatically
- `doctest` will be released to Hackage
The job only runs on pushes to `main`. So specifically:
- We should only bump the version if we intend to release
- We should not create tags manually

Automatically tag and publish to Hackage on version bumps

---

README.markdown
doctest.cabal
src/Interpreter.hs
src/Property.hs
test/InterpreterSpec.hs

Related GHC bug: https://gitlab.haskell.org/ghc/ghc/-/issues/20670

Workaround for a GHC bug with -XTemplateHaskell and ghci (fixes #303)

---

ghci-wrapper/src/Language/Haskell/GhciWrapper.hs

Was possibly a regression in 0.18.
We do not seem to cover this by the test-suite.

Re #292: GHC.IO.Handle.utf8 --> GHC.IO.Encoding.utf8

---

.github/workflows/build.yml

(this results in a stack overflow with GHC 9.4.*)

Don't run `doctest` with `cabal exec`

---

.github/workflows/cabal-doctest.yml
doctest.cabal
driver/cabal-doctest.hs
package.yaml

Based on https://github.com/mpickering/cabal-doctest-demo/blob/master/cabal-doctest
Follow-ups:

Add `cabal-doctest`

---

CHANGES.markdown
doctest.cabal
package.yaml

Changes in 0.22.5
- Add (experimental) `cabal-doctest` executable.  This is guarded behind a
flag for now, use `cabal install doctest -f -cabal-doctest` to install it.

Release 0.22.5

---

.github/workflows/cabal-doctest.yml
CHANGES.markdown
src/Cabal/Options.hs
test/Cabal/OptionsSpec.hs

cabal-doctest: Fix handling of options with optional arguments

---

src/Interpreter.hs

Don't display error links

---

.github/workflows/build.yml

Hi :)
I'm testing the library with GHC912 and the `haskell-actions` one is already supporting that. In this PR I did some updates to the GHA build job, in particular:
1. I've substituted the [hspec setup action](https://github.com/hspec/setup-haskell) with the [haskell-actions one](https://github.com/haskell-actions/setup). **Note**: `cabal update` is done by default by the used action.
2. Replaced `macOS-12` environment which is deprecated.
3. I've also run [actionlint](https://github.com/rhysd/actionlint) and addressed those issues. Here is the output of that tool:
```
.github/workflows/build.yml:121:9: shellcheck reported issue in this script: SC2046:warning:1:12: Quote this to prevent word splitting [shellcheck]
|
121 |       - run: cabal exec $(cabal list-bin spec)
|         ^~~~ …
```

Fix linting issues in GitHub Actions
